POST http://localhost:8888/users
Content-Type: application/json

{
  "name": "Tester",
  "email": "test@test.com",
  "password": "12341234"
}

###
POST http://localhost:8888/session
Content-Type: application/json

{
  "email": "test@test.com",
"password": "12341234"
}
