POST http://localhost:8888/users
Content-Type: application/json

{
  "name": "Tester",
  "email": "test@test.com",
  "password": "12341234"
}

###
POST http://localhost:8888/session
Content-Type: application/json

{
  "email": "test@test.com",
"password": "12341234"
}


###
POST localhost:8888/meeting-notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImV4cCI6MTcxNzc2ODE5MX0.csSOftreTIpJNpQaCDL_sbHGSJXJG4KoFB9tFadaC6I

{
    "title": "Meeting 1",
    "body": "Meeting 1 description keyword keyword keyword body body",
    "keywords": [
      {
        "keyword": "keyword",
        "count": 3
      },
      {
        "keyword": "body",
        "count": 2
      }
    ]
}