POST http://localhost:8888/users
Content-Type: application/json

{
  "name": "Tester",
  "email": "test@test.com",
  "password": "12341234"
}

###
POST http://localhost:8888/session
Content-Type: application/json

{
  "email": "test@test.com",
"password": "12341234"
}


###
POST localhost:8888/meeting-notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImV4cCI6MTcxODExNDQ2N30.XN6hSt8DQ9hn8EETfwBFY1oMUrJkpdZERFvjH1D10Mk

{
    "title": "Meeting 1",
    "body": "Meeting 1 description keyword keyword keyword body body",
    "keywords": [
      {
        "keyword": "keyword",
        "count": 3
      },
      {
        "keyword": "body",
        "count": 2
      }
    ]
}

###
GET localhost:8888/meeting-notes?page=0&size=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImV4cCI6MTcxODI4ODc3OH0.H9y7FfUfTP_z-swo_R1YBZSZmGuZUNASh_Tq7UcMJD8
